///Script "library" for working with menu of users (menu autogenerated from parameter files)
// must be placed in ...\Scripts\Include\
// http://akelpad.sourceforge.net/forum/viewtopic.php?p=8153#8153
// Version: 3.0 (2011.06.21)
//
/// Getting the value selected in the user menu (getSelectedMenuItem function)
//
// Menu automatically generated from the parameter files.
// Settings are located in files <current script name>. Param in the directory "[AkelPad]\AkelFiles\Plugs\Scripts\Params"
//
/// Получение значения, выбранного в пользовательском меню (функция getSelectedMenuItem)
//
// Меню автоматически формируются из соответствующего скрипту файла параметров.
// Параметры размещается в файлах <имя запускаемого скрипта>.param в дирректории "[AkelPad]\AkelFiles\Plugs\Scripts\Params"


var pScriptName = WScript.ScriptName;
var paramExt = ".param";
var bIgnoreMenu = false;		//если в файле параметров одна строка и bIgnoreMenu = True, тогда меню выводиться не будет


//Подключение общего скрипта-"библиотеки" вывода меню
if (! AkelPad.Include("ShowMenuCommon.js")) WScript.Quit();

//Arguments
if (hWndMain)
{
	if (WScript.Arguments.length >= 1)
	{
		pMenuFile = WScript.Arguments(0);		//имя *.param-файла
		
		if (WScript.Arguments.length >= 2)
			bIgnoreMenu = parseInt(WScript.Arguments(1));
	}
	
	if (!pMenuFile)
			pMenuFile = pScriptName.substring(0, pScriptName.indexOf(".")) + paramExt;		//Имя файла параметров берём по запускаемому скрипту
		pMenuFile = AkelPad.GetAkelDir(5) + "\\Params\\" + pMenuFile;
}


//Functions

function getSelectedMenuItem(pPOS_PLACE, pParsepProcType, bReturnStructure)
//pPOS_PLACE - возможность задавать позицию вывода меню; варианты см. в ShowMenuCommon.js var POS_ ...
//pParsepProcType	- каким образом будет распознаваться файл параметров:
//										0 - одно значение - одна строка; является надписью, выводимой в меню, применяется для простых случаев
//										INI - вариант записи параметров в виде: идентификатор = надпись, выводимая в меню
//										... - собственный парсер (необходимо будет добавить в var Parser)
//bReturnStructure		- в каком виде будет возвращаться результат:
//										false (0) - в виде текста (возврат надписи выбранного пункта меню)
//										true (1) - в виде структуры [идентификатор, MF_NORMAL, текст пункта меню] (для сложных случаев)
//		если пользователь может использовать любой вариант меню, то лучше передавать 1, а потом универсально анализировать результат pMenuItem[0]
//Примеры вызовов:
//						var pMenuLable = getSelectedMenuItem(POS_CARET, "0", 0);		- простой аналог ListBox'а
//						var pMenuItem = getSelectedMenuItem(POS_CARET, "INI", 1);		- аналог ListBox'а с псевдонимом (идентификатором)
//						var pMenuItem = getSelectedMenuItem(POS_CARET, "", 1);			- автоопределение типа парсера по данным в файле параметров; возвращает полную структуру выбранного пункта
{
	if (hWndMain)
	{
		var fso = new ActiveXObject("Scripting.FileSystemObject");
		if (fso.FileExists(pMenuFile) == true)
		{
			var lpItems=[];
			var nItem;

			var lpContent = AkelPad.ReadFile(pMenuFile);
			lpContent = lpContent.replace(/\r\n/g, "\r");
			lpContent = lpContent.replace(/\r{2,}/g, "\r");
			lpContent = trim(lpContent, "\r\n");
			if (lpContent)
			{
				var nEditItem = 1111;
				var lpArrayName = lpContent.split("\r");
				
				//Определение объекта-парсера
				var Parser =
				{
					proc0: function(lpArrayName, lpItems)
					{
						for (nItem = 0; nItem < lpArrayName.length; ++nItem)
						{
							pItem = lpArrayName[nItem];
							if (pItem)
								lpItems[nItem] = [pItem, MF_NORMAL, pItem];
						}
						return nItem;
					},
					
					procINI: function(lpArrayName, lpItems)
					{
						var oRegExp =
						{
							getPureValue: function(pStr)
							{
								return trim(pStr, " \t");
							}
						};
						
						var pItem;
						var iSep;
						var pValue;
						var pLabel;
						
						for (nItem = 0; nItem < lpArrayName.length; ++nItem)
						{
							pItem = lpArrayName[nItem];
							if (pItem)
							{
								iSep = pItem.lastIndexOf("=");
								if (iSep == -1)
								{
									pItem += "=";
									iSep = pItem.length;
								}
								pID = oRegExp.getPureValue(pItem.substr(0, iSep));
								pLabel = oRegExp.getPureValue(pItem.substr(iSep + 1));
								if (!pLabel)
									pLabel = "- надпись для " + pID + " не указана -";
								
								lpItems[nItem] = [pID, MF_NORMAL, pLabel];
							}
						}
						return nItem;
					}
				};
				
				//Автоопределение парсера (если не задан)
				if (!pParsepProcType)
				{
					if (lpArrayName[0].indexOf("=") == -1)
						pParsepProcType = "0";
					else
						pParsepProcType = "INI";
				}
				//формирование меню
				nItem = Parser["proc" + pParsepProcType](lpArrayName, lpItems);
				
				if (!(lpItems.length == 1 && bIgnoreMenu))
				{
					//Добавление возможности изменять настроечные файлы параметров
					lpItems[nItem] = ["", MF_SEPARATOR, ""];
					lpItems[nItem + 1] = [nEditItem, MF_NORMAL, "изменить меню..."];
					
					//Вывод меню на экран и получение выбранного Item'а
					nItem = ShowMenu(lpItems, pPOS_PLACE, pPOS_PLACE);
				}
				else
					nItem -= 1;
				
				if (nItem != -1)
				{
					if (lpItems[nItem][0] != nEditItem)
					{
						if (!bReturnStructure)
							return lpItems[nItem][0];					//Возвращаем выбранный пункт меню
						else
							return lpItems[nItem];						//Возвращаем полностью структуру
					}
					else
					{
						AkelPad.OpenFile(pMenuFile);		//Открываем файл параметров для внесения изменений
						WScript.Quit();
					}
				}
				else
					return '';
			}
			else
			{
				if (AkelPad.MessageBox(hWndEdit, "Файл параметров '" + pMenuFile + "' ПУСТ! Открыть его?", pScriptName, 4 /*MB_YESNO*/ + 48 /*MB_ICONEXCLAMATION*/) == 6)
					AkelPad.OpenFile(pMenuFile);
				WScript.Quit();
			}
		}
		else
		{
			if (AkelPad.MessageBox(hWndEdit, "Файл параметров '" + pMenuFile + "' НЕ СУЩЕСТВУЕТ! Создать его?", pScriptName, 4 /*MB_YESNO*/ + 48 /*MB_ICONEXCLAMATION*/) == 6)
			{
				AkelPad.SendMessage(hWndMain, 273 /*WM_COMMAND*/, 4101 /*IDM_FILE_NEW*/, 0);
				hWndEdit = AkelPad.GetEditWnd();
				AkelPad.SaveFile(hWndEdit, pMenuFile);
			}
			WScript.Quit();
		}
	}
}

function trim(pText, chars)
{
	return pText.replace(new RegExp("(^[" + chars + "])|([" + chars + "]+$)", "g"), "");
}